### PR TITLE
win: fix build with Qt 5.14 and MinGW

### PR DESCRIPTION
**Pull request by yeahitsjan**
This fixes my problems using QPointer in ``widgetssharedhelper_p.h``. Instead of using a raw pointer, we are still using QPointer. It could be possible to do an extended check somewhere if the pointer is already declared, example:
```
QPointer<QWidget> m_widget;
if (!m_widget) // if not already there
    m_widget = new QWidget;
```

### CODE REVIEW

**Comment by wangwenx190** [comment]
So with this PR applied, all the compilation errors are gone?

**Comment by yeahitsjan** [comment]
Yes, and it displays a very cool FramelessWindow!😄

**Comment by wangwenx190** [comment]
Thanks for your quick and easy fix!

**Comment by yeahitsjan** [comment]
I will extend it today or tomorrow with a simple version check. Give me some hours 😉

**Comment by wangwenx190** [comment]
> I will extend it today or tomorrow with a simple version check. Give me some hours 😉

OK, really thanks!
